In [64]:
import pandas as pd
import numpy as np
dataset = pd.read_csv('review.csv')

In [65]:
#dataset['stars'] = dataset.stars.map({'upvote':'0', 'downvote':'1'})
y = pd.get_dummies(dataset['stars'])

In [66]:
import re  
import nltk  
nltk.download('stopwords') 
from nltk.corpus import stopwords 
  
# for Stemming propose  
from nltk.stem.porter import PorterStemmer 
corpus = []  
for i in range(0, 10000):  
      
    # column : "Review", row ith 
    review = re.sub('[^a-zA-Z]', ' ', dataset['text'][i])  
      
    # convert all cases to lower cases 
    review = review.lower()  
      
    # split to array(default delimiter is " ") 
    review = review.split()  
      
    # creating PorterStemmer object to 
    # take main stem of each word 
    ps = PorterStemmer()  
      
    # loop for stemming each word 
    # in string array at ith row     
    review = [ps.stem(word) for word in review 
                if not word in set(stopwords.words('english'))]  
                  
    # rejoin all string array elements 
    # to create back into a string 
    review = ' '.join(review)   
      
    # append each string to create 
    # array of clean text  
    corpus.append(review)  


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\pathak\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [67]:
dataset.head(10)

text  stars
0  My wife took me here on my birthday for breakf...      0
1  I have no idea why some people give bad review...      0
2  love the gyro plate. Rice is so good and I als...      0
3  Rosie, Dakota, and I LOVE Chaparral Dog Park!!...      0
4  General Manager Scott Petello is a good egg!!!...      0
5  Quiessence is, simply put, beautiful.  Full wi...      0
6  Drop what you're doing and drive here. After I...      0
7  Luckily, I didn't have to travel far to make m...      0
8  Definitely come for Happy hour! Prices are ama...      0
9  Nobuo shows his unique talents with everything...      0

In [68]:
# Creating the Bag of Words model 
#max_features = 6000
from sklearn.feature_extraction.text import CountVectorizer 
cv = CountVectorizer(max_features = 7000)  
X = cv.fit_transform(corpus).toarray() 

In [69]:
y = dataset.iloc[:, 1].values  

In [70]:
from sklearn.cross_validation import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33) 

In [104]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None)

In [105]:
y_pred_NB = classifier.predict(X_test)
y_pred_NB

array([1, 0, 1, ..., 0, 0, 0], dtype=int64)

In [106]:
cm_NB = confusion_matrix(y_test, y_pred_NB) 
cm_NB

array([[1659, 1068],
       [ 310,  263]], dtype=int64)

In [107]:
TP_NB = 1659 #True Positives (Naive Bayes)
TN_NB = 263 #True Negatives (Naive Bayes)
FP_NB = 310 #False Positives (Naive Bayes)
FN_NB = 1068 #False Negatives (Naive Bayes)

In [108]:
Accuracy_NB = (TP_NB + TN_NB) / (TP_NB + TN_NB + FP_NB + FN_NB) 
Accuracy_NB 

0.5824242424242424

In [109]:
#DECISION TREE
from sklearn.tree import DecisionTreeClassifier
classifierDT = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifierDT.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [110]:
y_pred_DT = classifierDT.predict(X_test)
y_pred_DT

array([0, 1, 1, ..., 0, 0, 0], dtype=int64)

In [111]:
cm_DT = confusion_matrix(y_test, y_pred_DT) 
cm_DT

array([[2487,  240],
       [ 349,  224]], dtype=int64)

In [112]:
TP_NB = 2487 #True Positives (Naive Bayes)
TN_NB = 224 #True Negatives (Naive Bayes)
FP_NB = 349 #False Positives (Naive Bayes)
FN_NB = 240 #False Negatives (Naive Bayes)

In [113]:
Accuracy_NB = (TP_NB + TN_NB) / (TP_NB + TN_NB + FP_NB + FN_NB) 
Accuracy_NB 

0.8215151515151515

In [114]:
#RANDOM FOREST
from sklearn.ensemble import RandomForestClassifier
classifierRF = RandomForestClassifier(n_estimators = 500, criterion = 'entropy', random_state = 0)
classifierRF.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [116]:
y_pred_RF = classifierRF.predict(X_test)
y_pred_RF

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [117]:
cm_RF = confusion_matrix(y_test, y_pred_RF) 
cm_RF

array([[2718,    9],
       [ 504,   69]], dtype=int64)

In [118]:
TP_NB = 2718 #True Positives (Naive Bayes)
TN_NB = 69 #True Negatives (Naive Bayes)
FP_NB = 504 #False Positives (Naive Bayes)
FN_NB = 9 #False Negatives (Naive Bayes)

In [119]:
Accuracy_NB = (TP_NB + TN_NB) / (TP_NB + TN_NB + FP_NB + FN_NB) 
Accuracy_NB 

0.8445454545454546

In [120]:
# train a Naive Bayes model using X_train_dtm
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()
nb.fit(X_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [121]:
y_pred_NB = nb.predict(X_test)
y_pred_NB

array([0, 1, 0, ..., 0, 1, 0], dtype=int64)

In [122]:
cm_NB = confusion_matrix(y_test, y_pred_NB) 
cm_NB

array([[2515,  212],
       [ 217,  356]], dtype=int64)

In [123]:
TP_NB = 2515 #True Positives (Naive Bayes)
TN_NB = 356 #True Negatives (Naive Bayes)
FP_NB = 217 #False Positives (Naive Bayes)
FN_NB = 212 #False Negatives (Naive Bayes)

In [124]:
Accuracy_NB = (TP_NB + TN_NB) / (TP_NB + TN_NB + FP_NB + FN_NB) 
Accuracy_NB 

0.87